### ISSUE TITLE
Add Plop templates

### ISSUE THREAD

**Issue by devan-huapaya** [generalui/react-nextjs-boilerplate#21]
[Plop](https://plopjs.com/) can be used to help engineers quickly create components, in a system that requires each component to have several different files (test, styling, types, the component itself) from the command line. 

If used properly it can vastly speed up development time, and reduce errors / duplicate names.

**Comment by devan-huapaya** [comment]
Depends on https://github.com/generalui/react-nextjs-boilerplate/issues/26 structure being resolved

**Comment by jasepellerin** [comment]
I think this is a good way to help enforce the folder structure we've decided on. It's nice because it makes the right way the easy way.

**Comment by wesvance** [comment]
+1 on this for me
