### ISSUE TITLE
Add local storage persistence to hooks for redux 

### ISSUE THREAD

**Issue by devan-huapaya** [generalui/react-nextjs-boilerplate#24]
Redux should be able to save desired states to local storage this is needed in every react project and should be included in the boilerplate

**Comment by devan-huapaya** [comment]
depends on https://github.com/generalui/react-nextjs-boilerplate/issues/15

**Comment by AFrey95** [comment]
What are the configuration parameters for this? Local storage may not always be appropriate for every project.
